In [1]:
import numpy as np


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


create a numpy ndarray object,the array object in numpy is called as ndarray

In [3]:
import numpy as np
sai=np.array([1,2,3,4,5])
print(sai)
print(type(sai))

[1 2 3 4 5]
<class 'numpy.ndarray'>


we can use a tuple to create a numpy array

In [4]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


we can create a 0-D ARRAY WITH THE VALUE 42

In [5]:
import numpy as np
arr=np.array(42)
print(arr)

42


we can create a 1-D array containingf the values 1,2,3,4,5

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


An array that has 1-d arrays as its elements is called a 2-D array,they are often used to represent the matrix or the order tensors

In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [10]:
arr=np.array([[4,5,6],[7,8,9]])
print(arr)

[[4 5 6]
 [7 8 9]]


An array that has 2-d arrys matrices as its elements is called an 3-d array

In [11]:
arr=np.array([[[2,3,4],[7,8,9]],[[1,2,3],[4,5,6]]])
print(arr)

[[[2 3 4]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]]]


numpy arrays provides the ndim attribute that returns as an integer that tells us how many dimension the array has

In [12]:
a=np.array(43)
b=np.array([1,2,3,4]) #one dimension
c=np.array([[1,2,3],[4,5,6]]) # two dimension
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) #three dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


we can create 5 dimensional array and verify that it has 5 dimensions

In [16]:
arr=np.array([1,2,3,4],ndmin=5) #ndmin helps us to create the array of desired dimension
print(arr)
print('number of dimension :',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension : 5


we can acess the array elements ,it is also known as array indexing we van access an array element by referring to its index number,the indexes in the numpy array starts with 0 

In [18]:
arr=np.array([1,2,3,4])
print(arr[0])

1


In [19]:
arr=np.array([1,2,3,4])
print(arr[1])

2


In [20]:
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


Access the 2d arrays elements we can use the comma seperated integers representing the dimension and the index of the element,think of the 2 d arry as the dimension so that dimension represent the row and index represent the columns

In [22]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) #2d array
print("second element on the first row:",arr[0,1])

second element on the first row: 2


access the element on the second row 2nd row 5th column

In [24]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # this is a 2d array
print("get the fifth element in the second row",arr[1,4]) #it is acessing the element from the index four i row 2

get the fifth element in the second row 10


In [29]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#now we need to acess the third element of second array of the first array
print(arr[0,1,2])
print(arr[1,1,2])
print(arr[1,1,0])
print(arr[1,0,2])

6
12
10
9


we can use the negetive indexing from the 2nd dim


In [31]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("last element from the 2nd dimension",arr[1,-2])

last element from the 2nd dimension 9


slicing the array:slice the elements index from 1 to index 5


In [38]:
for i in np.linspace(-5.5,5,10):
    print(i)

-5.5
-4.333333333333333
-3.1666666666666665
-2.0
-0.833333333333333
0.3333333333333339
1.5
2.666666666666668
3.833333333333334
5.0


In [39]:
for i in np.linspace(10,11,20,retstep=True):
    print(i) #suppose if you want to get the numbers between 10 and 11 and if you want to get 20 numbers between them

[10.         10.05263158 10.10526316 10.15789474 10.21052632 10.26315789
 10.31578947 10.36842105 10.42105263 10.47368421 10.52631579 10.57894737
 10.63157895 10.68421053 10.73684211 10.78947368 10.84210526 10.89473684
 10.94736842 11.        ]
0.05263157894736842


In [40]:
x=np.linspace(0,200,100,retstep=True)
print(x)

(array([  0.        ,   2.02020202,   4.04040404,   6.06060606,
         8.08080808,  10.1010101 ,  12.12121212,  14.14141414,
        16.16161616,  18.18181818,  20.2020202 ,  22.22222222,
        24.24242424,  26.26262626,  28.28282828,  30.3030303 ,
        32.32323232,  34.34343434,  36.36363636,  38.38383838,
        40.4040404 ,  42.42424242,  44.44444444,  46.46464646,
        48.48484848,  50.50505051,  52.52525253,  54.54545455,
        56.56565657,  58.58585859,  60.60606061,  62.62626263,
        64.64646465,  66.66666667,  68.68686869,  70.70707071,
        72.72727273,  74.74747475,  76.76767677,  78.78787879,
        80.80808081,  82.82828283,  84.84848485,  86.86868687,
        88.88888889,  90.90909091,  92.92929293,  94.94949495,
        96.96969697,  98.98989899, 101.01010101, 103.03030303,
       105.05050505, 107.07070707, 109.09090909, 111.11111111,
       113.13131313, 115.15151515, 117.17171717, 119.19191919,
       121.21212121, 123.23232323, 125.25252525, 127.2

In [41]:
x=np.linspace(0,5,10,endpoint=False) #endpoint to false omits the end value
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


initialize an array using the function

In [43]:
def f(i,j):
    return 2*i*j
np.fromfunction(f,(4,3))
np.fromfunction(lambda i,j:2*i*j,(4,3))


array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [48]:
a=np.array(((1,2,3,),(5,6,7,)))
a.shape   # 2 rows and 3 columns

(2, 3)

In [51]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[89,79]]])
a.shape
print(a)
print(a.shape) #three matrix(tuples) of 2 rows and 2 columns

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [89 79]]]
(3, 2, 2)


In [58]:
x=np.linspace(1,5,5)
x**3
print(x)

[1. 2. 3. 4. 5.]


In [59]:
y=np.exp(-np.linspace(0,2,5))
np.sin(x-y)

array([ 0.        ,  0.98431873,  0.48771645, -0.59340065, -0.98842844])

marix multiplication numpy


In [2]:
import numpy as np
a=np.array(((1,2),(2,1)))
b=a
a*b #elementwisw multiplication

array([[1, 4],
       [4, 1]])

In [5]:
np.matmul(a,b)
a.dot(b)


array([[5, 4],
       [4, 5]])

comparison and logical operations

In [6]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([1,2])
np.dot(b,a)

array([ 5,  8, 11])

In [7]:
a>100

array([[False, False, False],
       [False, False, False]])

Numpy special values nan and inf
numpy defines two special values to represent the outcomes of calculation which are not mathematically defined or finite the value np.nan represents the oucome of the calculations which is not defined np.inf represents the infinity

In [11]:
#creating an NxN magic square N must be odd
N=5
msquare=np.zeros((N,N),dtype=int)
n=1
i,j=0,N/2

while n<=N**2:
    msquare[i,j]=n
    n +=1
    newi, newj = (i-1)%N, (j+1)%N
    if msquare[newi,newj]:
        i +=1
    else:
        i, j = newi, newj
msquare



IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

flatten and ravel
flatten returns as independent copy of the elements and is generally slower than flattened array

In [14]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b=a.flatten() #create a independent,flatten copy of a
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
b[3]=0
b

array([1, 2, 3, 0, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
c=a.ravel()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

flatten

In [18]:
a=np.array([(1,2,3,4),(3,1,4,2)])
print("the original array is",a)
c=a.flatten() #convert into 1-d array
print("the flattened array after the process",c)

the original array is [[1 2 3 4]
 [3 1 4 2]]
the flattened array after the process [1 2 3 4 3 1 4 2]


ravel()

In [3]:
a=np.array([(1,2,3,4),(3,1,4,2)])
print("the original array is",a)
ra=np.ravel(a) #This demonstrates that ravel() returns a shallow copy of the Numpy input array.
print("the flattened array using the rave function is",ra)

the original array is [[1 2 3 4]
 [3 1 4 2]]
the flattened array using the rave function is [1 2 3 4 3 1 4 2]


resize and reshape
resize is the inverse method to flatten


In [4]:
a=np.linspace(1,8,8)
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [5]:
a.resize(2,2,2)#reshapes a in place doesnt return anything
a

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [8]:
a=np.array([[1,2,],[3,4]])
i=np.resize(a,(3,2))
i 


array([[1, 2],
       [3, 4],
       [1, 2]])

reshape method  reshape does ot return the original array but return the changed array

In [11]:
 #creating an array 
gfg = np.array([1, 2, 3, 4, 5, 6]) 
print("Original array:")
display(gfg)  
  
# using reshape()
print("Changed array")
display(gfg.reshape(2, 3)) #display the array in 2 rows and 3 columns
    
print("Original array:")
display(gfg)


Original array:


array([1, 2, 3, 4, 5, 6])

Changed array


array([[1, 2, 3],
       [4, 5, 6]])

Original array:


array([1, 2, 3, 4, 5, 6])

Transposing an array-returns array with the axes transposed
transposing a one dimensional arrayu retuens the array unchanged


In [20]:
a=np.linspace(1,16,16)
a=a.reshape(2,2,4)
print(a)
print(a.transpose())
print(a.transpose().shape)


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
[[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]
(4, 2, 2)


In [21]:
a.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

In [22]:
b=np.array([100,101,102,103])
b.transpose() # transposing a one imensional array returns the array unchanged

array([100, 101, 102, 103])

merging and splitting the arrays


In [23]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


spliting the 2d array into three 2d arrays

In [24]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


split the 2d array into three 2d arrays along the rows

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [26]:
#hsplit () method to split the array 2-D 
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [29]:
#hstack function  used to stack the input of sequence array  horizontally
in_arr1=np.array([1,2,3])
print("the first input array",in_arr1)

in_arr2=np.array([4,5,6])
print("the second input array",in_arr2)

#stavking the two arrays horizontally
out_stack=np.hstack((in_arr1,in_arr2))
print("the ouput stacked array is ",out_stack)

the first input array [1 2 3]
the second input array [4 5 6]
the ouput stacked array is  [1 2 3 4 5 6]


In [30]:
#dstack
in_arr1=np.array([1,2,3])
print("the first input array",in_arr1)

in_arr2=np.array([4,5,6])
print("the second input array",in_arr2)
print(np.dstack((in_arr1,in_arr2)))

the first input array [1 2 3]
the second input array [4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


AttributeError: module 'numpy' has no attribute 'linspapce'

In [36]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
#index values can be negetive also
arr=x[np.array([1,3,-4])]
print("the elements are ",arr)


NameError: name 'x' is not defined

In [37]:
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
ia=[1,4,5]
a[ia]

array([2., 5., 6.])

In [39]:
a=np.linspace(1,12,12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [40]:
ia=np.array((1,0),(2,1))
ja=np.array((0,1),(1,2))
a[ia,ja]


TypeError: Cannot interpret '2' as a data type

In [43]:
arr=np.arange(5*5).reshape(5,5)
print(arr.shape)
#promoting the 2d array into 5d array
#arr[none,....None,none]
arr_5d=arr[np.newaxis,...,np.newaxis,np.newaxis]
print(arr_5d.shape)

(5, 5)
(1, 5, 5, 1, 1)


meshes

In [44]:
x=np.linspace(0,5,6)
y=np.linspace(0,3,4)
X,Y=np.meshgrid(x,y)
X

array([[0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.]])

In [45]:
Y

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.]])

the x array is repeated as rows down x and y arrays as columns across Y

In [46]:
X,Y=np.meshgrid(x,y,sparse=True)
x,y

(array([0., 1., 2., 3., 4., 5.]), array([0., 1., 2., 3.]))

In [47]:
##Broadcasting The term broadcasting refers to how numpy treats arrays with different Dimension during arithmetic operations 
##before broadcasting
a=np.array((0,1,2))
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [48]:
#broadcasting allw us to add a scalar 
a+5

array([5, 6, 7])

In [49]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [52]:
a=np.arange(2) #arange will generate sequence of numbers in sequential manner
b=np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1]
[[0]
 [1]
 [2]]


In [53]:
a+b

array([[0, 1],
       [1, 2],
       [2, 3]])

Max and min values in the array

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
#finding the maximum and 
#finding the min element
max_element=np.max(arr)
min_element=np.min(arr)
#printing the result
print("the max element in the arrat is",max_element)
print("the min element in the array is",min_element)

the max element in the arrat is 7
the min element in the array is 1


In [6]:
a=np.array([[3,0,1,-1],[2,-1,-2,4],[1,7,0,4]])
a

array([[ 3,  0,  1, -1],
       [ 2, -1, -2,  4],
       [ 1,  7,  0,  4]])

In [7]:
a.flatten()[9]

7

In [8]:
print(np.argmin(a))
print(np.argmax(a))

6
9


In [9]:
a.max()

7

In [11]:
print(a.max(axis=0)) #maxima in each column
print(a.min(axis=1)) #minima in each row

[3 7 1 4]
[-1 -2  0]


In [12]:
a.argmin()

6

In [13]:
a.ravel()[a.argmin()]==a.min()

True

In [14]:
print(a.argmax(axis=0)) #row indexes of maxima in each column

[0 2 0 1]


In [15]:
print(a.argmax(axis=1))

[0 3 1]


sorting an array

In [16]:
a=np.sort([5,-1,2,4,0,4])
a.sort()
print(a)

[-1  0  2  4  4  5]


In [18]:
b=np.array([[0,3,-2],[7,1,3],[4,0,-1]])
b

array([[ 0,  3, -2],
       [ 7,  1,  3],
       [ 4,  0, -1]])

In [20]:
b.sort() #sorting along each row
b

array([[-2,  0,  3],
       [ 1,  3,  7],
       [-1,  0,  4]])

In [22]:
b.sort(axis=0)
print(b)

[[-2  0  3]
 [-1  0  4]
 [ 1  3  7]]


In [23]:
a=np.array([3,0,-1,1])
np.argsort(a)

array([2, 1, 3, 0], dtype=int64)

In [24]:
a[np.argsort(a)]

array([-1,  0,  1,  3])

In [25]:
a=np.array([1,2,3,4])
np.searchsorted(a,3.5)

3

In [27]:
np.searchsorted(a,(3.5,0,1.1))

array([3, 0, 1], dtype=int64)

sTATISTICS


In [28]:
a=np.sqrt(np.linspace(-2,2,4))
print(a)

[       nan        nan 0.81649658 1.41421356]


C:\Users\Msc 1\AppData\Local\Temp\ipykernel_636\1251473525.py:1: RuntimeWarning: invalid value encountered in sqrt
  a=np.sqrt(np.linspace(-2,2,4))


In [29]:
np.min(a),np.max(a)

(nan, nan)

In [30]:
np.nanmax(a),np.nanmin(a)

(1.4142135623730951, 0.8164965809277259)

In [31]:
np.argmax(a),np.argmin(a)

(0, 0)

In [33]:
np.nanargmin(a),np.nanargmax(a)

(2, 3)

In [34]:
b=np.array([1,-5,6,2])
c=np.array([0,np.nan,-1,3])
np.fmax(b,c)

array([ 1., -5.,  6.,  3.])

In [35]:
np.fmin(b,c)

array([ 0., -5., -1.,  2.])

percentiles

In [2]:
##np.percentile method returns the specified percentile

In [7]:
import numpy as np
arr = [20, 2, 7, 1, 34]
print("arr : ", arr)
print("50th percentile of arr : ",
       np.percentile(arr, 50))
print("25th percentile of arr : ",
       np.percentile(arr, 25))
print("75th percentile of arr : ",
       np.percentile(arr, 75))


arr :  [20, 2, 7, 1, 34]
50th percentile of arr :  7.0
25th percentile of arr :  2.0
75th percentile of arr :  20.0


AttributeError: 'list' object has no attribute 'percentile'

In [8]:
##sample statistics
x=np.array([1.,4.,9,16])
np.mean(x)

7.5

In [9]:
np.median(x)

6.5

In [11]:
np.average(x, weights=[0.3,0,1,0])

7.153846153846154

In [14]:
x=np.array([[1,8,27],[-0.5,1,0.]])
av,sw=np.average(x,weights=[0,1.,0.1], axis=1,returned=True)
print(av)
print(sw)

[9.72727273 0.90909091]
[1.1 1.1]


In [15]:
x=np.array([1.,2.,3.,4.])
np.std(x)

1.118033988749895

In [16]:
np.std(x,ddof=1)

1.2909944487358056

In [17]:
np.sqrt(np.var(x))

1.118033988749895

In [18]:
np.var(x,ddof=1)

1.6666666666666667

In [24]:
x=np.array([[0.1,0.3,0.4,0.8,0.9],[3.1,3.8,0.4,1.8,5.9],[10,8.3,3.4,2.8,0.9],[10.2,18.3,3.34,3.48,1.9]])
print(x)
x1=np.cov(x)
print(x1)


[[ 0.1   0.3   0.4   0.8   0.9 ]
 [ 3.1   3.8   0.4   1.8   5.9 ]
 [10.    8.3   3.4   2.8   0.9 ]
 [10.2  18.3   3.34  3.48  1.9 ]]
[[ 0.115    0.215   -1.2     -1.5675 ]
 [ 0.215    4.315   -0.4875   2.0775 ]
 [-1.2     -0.4875  15.017   21.9056 ]
 [-1.5675   2.0775  21.9056  47.18508]]


In [26]:
print(np.var(x1,axis=1,ddof=1))

[  0.82371823   4.61850417 132.22172954 500.66549478]


In [27]:
print(np.corrcoef(x))

[[ 1.          0.30521027 -0.91314708 -0.67290891]
 [ 0.30521027  1.         -0.06056094  0.14559561]
 [-0.91314708 -0.06056094  1.          0.82292682]
 [-0.67290891  0.14559561  0.82292682  1.        ]]


In [28]:
x=np.array([1,2,3,4,5])
y=np.array([0.08,0.32,0.41,0.48,0.86])
print(np.cov(x,y))

[[2.5    0.43  ]
 [0.43   0.0806]]


In [30]:
print(np.corrcoef(x,y))

[[1.         0.95792373]
 [0.95792373 1.        ]]


In [32]:
##special distributions

In [34]:
np.random.seed(3)
np.random.randint(1,10,10)

array([9, 4, 9, 9, 1, 6, 4, 6, 8, 7])

In [35]:
np.random.randint(1,10,size=5)

array([1, 5, 8, 9, 2])

In [36]:
np.random.seed(42)
np.random.randint(1,10,10)

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4])

In [37]:
#generate random floating point numbers
np.random.random_sample((2,3))

array([[1.42866818e-01, 6.50888473e-01, 5.64115790e-02],
       [7.21998772e-01, 9.38552709e-01, 7.78765841e-04]])

In [38]:
np.random.rand(2,3)

array([[0.99221156, 0.61748151, 0.61165316],
       [0.00706631, 0.02306243, 0.52477466]])

In [39]:
np.random.randint(4)

2

In [40]:
np.random.randint(4,size=10)

array([1, 3, 3, 3, 3, 2, 1, 1, 2, 1])

In [41]:
np.random.randint(1,4,(3,5))

array([[3, 3, 1, 3, 1],
       [3, 3, 1, 1, 3],
       [2, 1, 2, 2, 2]])

In [42]:
np.random.normal()

-0.600638689918805

In [43]:
np.random.normal(scale=5,size=3) #mean=0


array([-1.45846875, -3.00853306,  9.26139092])

In [44]:
x=np.random.normal(100.,8.,size=100)
print(np.mean(x))
print(np.std(x,ddof=1))

99.52885522852107
7.561812092690463


In [45]:
np.random.gamma?

In [46]:
import numpy as np
A=np.array([[1,-2,0,0],[0,7,2,-4],[1,2,3,5],[1,2,5,6]])
b=np.array([0,0,10,15])
np.linalg.solve(A,b)

array([-0.2247191 , -0.11235955,  2.07865169,  0.84269663])